defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default

plugins:
  - jekyll-readme-index
  - jekyll-titles-from-headings

kramdown:
  input: GFM
  syntax_highlighter: rouge

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: true

titles_from_headings:
  enabled: false
  strip_title: false
  collections: false
